@extends('layouts.admin')

@section('title', 'Mata Pelajaran — Panel Admin')
@section('admin_page', 'subjects')

@section('content')
    <header class="admin-page-head"><div class="admin-breadcrumb"><span><a href="{{ route('admin.dashboard') }}">Admin</a></span><span>Mata Pelajaran</span></div><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3"><div><span class="eyebrow">Data akademik</span><h1>Mata pelajaran.</h1><p class="text-muted-warm mb-0">Kelola kode, nama, deskripsi, dan status mapel yang digunakan pada penugasan.</p></div><a class="btn btn-primary" href="{{ route('admin.subjects.create') }}">+ Tambah Mapel</a></div></header>
    <form action="{{ route('admin.subjects.index') }}" method="get" class="admin-filter row g-2 align-items-end mb-4"><div class="col-lg-7"><label class="form-label" for="subject_search">Cari mata pelajaran</label><input class="form-control" id="subject_search" name="q" type="search" value="{{ request('q') }}" placeholder="Kode atau nama"></div><div class="col-lg-3"><label class="form-label" for="subject_status">Status</label><select class="form-select" id="subject_status" name="status"><option value="">Semua status</option><option value="active" @selected(request('status') === 'active')>Aktif</option><option value="inactive" @selected(request('status') === 'inactive')>Nonaktif</option></select></div><div class="col-lg-2 d-grid"><button class="btn btn-outline-primary" type="submit">Terapkan</button></div></form>
    <section class="admin-card"><div class="admin-card-header"><div><span class="eyebrow">Hasil data</span><h2 class="h3 mb-0">{{ $subjects->total() }} mata pelajaran</h2></div>@if(request()->hasAny(['q','status']))<a class="small" href="{{ route('admin.subjects.index') }}">Reset filter</a>@endif</div>
        @if($subjects->isEmpty())<div class="empty-state m-3"><span class="empty-state-mark">—</span><span class="eyebrow">Tidak ada hasil</span><h2>{{ request()->hasAny(['q','status']) ? 'Mata pelajaran tidak ditemukan.' : 'Mata pelajaran belum tersedia.' }}</h2><p class="text-muted-warm">{{ request()->hasAny(['q','status']) ? 'Ubah kata kunci atau status yang dipilih.' : 'Tambahkan mata pelajaran pertama untuk mulai menyusun data akademik.' }}</p></div>@else
            <div class="table-responsive table-responsive-stack"><table class="table table-admin"><thead><tr><th>Kode</th><th>Mata pelajaran</th><th>Deskripsi</th><th>Penugasan</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@foreach($subjects as $subject)<tr><td data-label="Kode"><strong>{{ $subject->code }}</strong></td><td data-label="Mata pelajaran">{{ $subject->name }}</td><td data-label="Deskripsi">{{ str($subject->description ?: '—')->limit(70) }}</td><td data-label="Penugasan">{{ $subject->teaching_assignments_count }} penugasan</td><td data-label="Status"><span class="badge {{ $subject->is_active ? 'badge-soft-success' : 'text-bg-light' }}">{{ $subject->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td data-label="Aksi" class="text-end"><div class="row-actions"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.subjects.edit', $subject) }}">Edit</a><form action="{{ route('admin.subjects.toggle-status', $subject) }}" method="post" data-confirm="{{ $subject->is_active ? 'Nonaktifkan' : 'Aktifkan' }} mata pelajaran {{ $subject->name }}?">@csrf @method('PATCH')<button class="btn btn-sm {{ $subject->is_active ? 'btn-outline-danger' : 'btn-outline-primary' }}" type="submit">{{ $subject->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></form><form action="{{ route('admin.subjects.destroy', $subject) }}" method="post" data-confirm="Hapus mata pelajaran {{ $subject->name }}?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit">Hapus</button></form></div></td></tr>@endforeach</tbody></table></div>@if($subjects->hasPages())<div class="admin-card-footer">{{ $subjects->links() }}</div>@endif
        @endif
    </section>
@endsection
