@extends('layouts.admin')

@php($editing = $period->exists)
@section('title', ($editing ? 'Edit' : 'Tambah').' Periode Akademik — Panel Admin')
@section('admin_page', 'periods')

@section('content')
    <header class="admin-page-head"><div class="admin-breadcrumb"><span><a href="{{ route('admin.dashboard') }}">Admin</a></span><span><a href="{{ route('admin.periods.index') }}">Periode Akademik</a></span><span>{{ $editing ? 'Edit' : 'Tambah' }}</span></div><span class="eyebrow">Tahun ajaran & semester</span><h1>{{ $editing ? 'Edit periode.' : 'Tambah periode.' }}</h1><p class="text-muted-warm mb-0">Mengaktifkan periode ini akan menonaktifkan periode sebelumnya dalam satu transaksi.</p></header>
    @include('admin.partials.validation-errors')
    @if($editing && ($referenced ?? false))<div class="alert alert-warning" role="status">Periode ini sudah digunakan oleh kelas. Tahun ajaran, semester, serta tanggal mulai dan selesai dikunci untuk menjaga histori; status aktif tetap dapat diubah.</div>@endif
    <form action="{{ $editing ? route('admin.periods.update', $period) : route('admin.periods.store') }}" method="post">@csrf @if($editing) @method('PUT') @endif<section class="admin-card"><div class="admin-card-header"><div><span class="eyebrow">Data periode</span><h2 class="h3 mb-0">Rentang akademik</h2></div></div><div class="admin-card-body"><div class="row g-3">
        <div class="col-md-6"><label class="form-label" for="academic_year">Tahun ajaran <span class="required-mark">*</span></label><input class="form-control @error('academic_year') is-invalid @enderror" id="academic_year" name="academic_year" value="{{ old('academic_year', $period->academic_year) }}" placeholder="2027/2028" required>@error('academic_year')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="semester">Semester <span class="required-mark">*</span></label><select class="form-select @error('semester') is-invalid @enderror" id="semester" name="semester" required><option value="">Pilih semester</option>@foreach($semesters as $semester)<option value="{{ $semester->value }}" @selected(old('semester', $period->semester?->value) === $semester->value)>{{ $semester->label() }}</option>@endforeach</select>@error('semester')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="start_date">Tanggal mulai <span class="required-mark">*</span></label><input class="form-control @error('start_date') is-invalid @enderror" id="start_date" name="start_date" type="date" value="{{ old('start_date', $period->start_date?->format('Y-m-d')) }}" required>@error('start_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="end_date">Tanggal selesai <span class="required-mark">*</span></label><input class="form-control @error('end_date') is-invalid @enderror" id="end_date" name="end_date" type="date" value="{{ old('end_date', $period->end_date?->format('Y-m-d')) }}" required>@error('end_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked(old('is_active', $period->is_active))><label class="form-check-label" for="is_active">Jadikan periode aktif setelah disimpan</label></div></div>
    </div></div><div class="admin-card-footer d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.periods.index') }}">Batal</a><button class="btn btn-primary" type="submit">Simpan Periode</button></div></section></form>
@endsection
