@extends('layouts.admin')

@section('title', 'Periode Akademik — Panel Admin')
@section('admin_page', 'periods')

@section('content')
    <header class="admin-page-head"><div class="admin-breadcrumb"><span><a href="{{ route('admin.dashboard') }}">Admin</a></span><span>Periode Akademik</span></div><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3"><div><span class="eyebrow">Tahun ajaran & semester</span><h1>Periode akademik.</h1><p class="text-muted-warm mb-0">Satu periode aktif menjadi konteks utama portal siswa dan data akademik.</p></div><a class="btn btn-primary" href="{{ route('admin.periods.create') }}">+ Tambah Periode</a></div></header>
    <section class="admin-card"><div class="admin-card-header"><div><span class="eyebrow">Riwayat periode</span><h2 class="h3 mb-0">{{ $periods->total() }} periode</h2></div></div>
        @if($periods->isEmpty())<div class="empty-state m-3"><span class="empty-state-mark">—</span><span class="eyebrow">Belum ada data</span><h2>Periode akademik belum tersedia.</h2><p class="text-muted-warm">Tambahkan periode pertama dan tandai aktif bila sudah digunakan.</p><a class="btn btn-primary" href="{{ route('admin.periods.create') }}">Tambah Periode</a></div>@else
            <div class="table-responsive table-responsive-stack"><table class="table table-admin"><thead><tr><th>Tahun ajaran</th><th>Semester</th><th>Rentang</th><th>Kelas</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@foreach($periods as $period)<tr><td data-label="Tahun ajaran"><strong>{{ $period->academic_year }}</strong></td><td data-label="Semester">{{ $period->semester->label() }}</td><td data-label="Rentang">{{ $period->start_date->translatedFormat('d M Y') }}—{{ $period->end_date->translatedFormat('d M Y') }}</td><td data-label="Kelas">{{ $period->classes_count }} kelas</td><td data-label="Status"><span class="badge {{ $period->is_active ? 'badge-soft-success' : 'text-bg-light' }}">{{ $period->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td data-label="Aksi" class="text-end"><div class="row-actions"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.periods.edit', $period) }}">Edit</a>@if($period->is_active)<form action="{{ route('admin.periods.deactivate', $period) }}" method="post" data-confirm="Nonaktifkan periode {{ $period->academic_year }} {{ $period->semester->label() }}?">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-danger" type="submit">Nonaktifkan</button></form>@else<form action="{{ route('admin.periods.activate', $period) }}" method="post" data-confirm="Aktifkan periode ini dan nonaktifkan periode aktif sebelumnya?">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-primary" type="submit">Aktifkan</button></form><form action="{{ route('admin.periods.destroy', $period) }}" method="post" data-confirm="Hapus periode {{ $period->academic_year }} {{ $period->semester->label() }}?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit">Hapus</button></form>@endif</div></td></tr>@endforeach</tbody></table></div>@if($periods->hasPages())<div class="admin-card-footer">{{ $periods->links() }}</div>@endif
        @endif
    </section>
@endsection
