@extends('layouts.admin')

@section('title', 'Data Siswa & Akun — Panel Admin')
@section('admin_page', 'students')

@section('content')
    <header class="admin-page-head"><div class="admin-breadcrumb"><span><a href="{{ route('admin.dashboard') }}">Admin</a></span><span>Siswa &amp; Akun</span></div><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3"><div><span class="eyebrow">Data siswa dan akses</span><h1>Data siswa.</h1><p class="text-muted-warm mb-0">Kelola biodata dan akun siswa secara atomik tanpa menampilkan kata sandi.</p></div><a class="btn btn-primary" href="{{ route('admin.students.create') }}">+ Tambah Siswa</a></div></header>

    <form action="{{ route('admin.students.index') }}" method="get" class="admin-filter row g-2 align-items-end mb-4"><div class="col-lg-7"><label class="form-label" for="student_search">Cari siswa</label><input class="form-control" id="student_search" name="q" type="search" value="{{ request('q') }}" placeholder="Nama, NISN, NIS, atau username"></div><div class="col-lg-3"><label class="form-label" for="student_status">Status siswa/akun</label><select class="form-select" id="student_status" name="status"><option value="">Semua status</option><option value="active" @selected(request('status') === 'active')>Aktif</option><option value="inactive_account" @selected(request('status') === 'inactive_account')>Akun nonaktif</option><option value="alumni" @selected(request('status') === 'alumni')>Alumni</option><option value="archived" @selected(request('status') === 'archived')>Diarsipkan</option></select></div><div class="col-lg-2 d-grid"><button class="btn btn-outline-primary" type="submit">Terapkan</button></div></form>

    <section class="admin-card"><div class="admin-card-header"><div><span class="eyebrow">Hasil data</span><h2 class="h3 mb-0">{{ $students->total() }} siswa ditemukan</h2></div>@if(request()->hasAny(['q','status']))<a class="small" href="{{ route('admin.students.index') }}">Reset filter</a>@endif</div>
        @if($students->isEmpty())
            <div class="empty-state m-3"><span class="empty-state-mark">—</span><span class="eyebrow">Tidak ada hasil</span><h2>{{ request()->hasAny(['q','status']) ? 'Siswa tidak ditemukan.' : 'Data siswa belum tersedia.' }}</h2><p class="text-muted-warm">{{ request()->hasAny(['q','status']) ? 'Ubah kata kunci atau status yang dipilih.' : 'Tambahkan siswa pertama beserta akun loginnya.' }}</p></div>
        @else
            <div class="table-responsive table-responsive-stack"><table class="table table-admin"><thead><tr><th>Siswa</th><th>NISN</th><th>Kelas aktif</th><th>Akun</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@foreach($students as $student)
                @php($enrollment = $student->activeEnrollment)
                <tr><td data-label="Siswa"><div class="d-flex align-items-center gap-2"><span class="avatar">{{ strtoupper(mb_substr($student->name, 0, 2)) }}</span><div><strong>{{ $student->name }}</strong><span class="d-block small text-muted-warm">NIS {{ $student->nis ?: '—' }}</span></div></div></td><td data-label="NISN">{{ $student->nisn }}</td><td data-label="Kelas aktif">@if($enrollment)<span class="badge badge-soft-success">{{ $enrollment->schoolClass->name }}</span><span class="d-block small text-muted-warm">{{ $enrollment->schoolClass->academicPeriod->academic_year }} · {{ $enrollment->schoolClass->academicPeriod->semester->label() }}</span>@else — @endif</td><td data-label="Akun"><span class="badge {{ $student->user->is_active ? 'badge-soft-success' : 'text-bg-warning' }}">{{ $student->user->is_active ? 'Aktif' : 'Nonaktif' }}</span><span class="d-block small text-muted-warm">{{ $student->user->username }}</span></td><td data-label="Status">{{ $student->status->label() }}</td><td data-label="Aksi" class="text-end"><div class="row-actions"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.students.show', $student) }}">Detail</a><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.students.edit', $student) }}">Edit</a><form action="{{ route('admin.students.toggle-account', $student) }}" method="post" data-confirm="{{ $student->user->is_active ? 'Nonaktifkan' : 'Aktifkan' }} akun {{ $student->name }}?">@csrf @method('PATCH')<button class="btn btn-sm {{ $student->user->is_active ? 'btn-outline-danger' : 'btn-outline-primary' }}" type="submit">{{ $student->user->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></form></div></td></tr>
            @endforeach</tbody></table></div>@if($students->hasPages())<div class="admin-card-footer">{{ $students->links() }}</div>@endif
        @endif
    </section>
@endsection
