@extends('layouts.admin')

@section('title', $student->name.' — Data Siswa')
@section('admin_page', 'students')

@section('content')
    <header class="admin-page-head"><div class="admin-breadcrumb"><span><a href="{{ route('admin.dashboard') }}">Admin</a></span><span><a href="{{ route('admin.students.index') }}">Siswa &amp; Akun</a></span><span>Detail</span></div><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3"><div><span class="eyebrow">NISN {{ $student->nisn }}</span><h1>{{ $student->name }}</h1><p class="text-muted-warm mb-0">{{ $student->status->label() }} · akun {{ $student->user->is_active ? 'aktif' : 'nonaktif' }}</p></div><a class="btn btn-primary" href="{{ route('admin.students.edit', $student) }}">Edit Siswa</a></div></header>
    <div class="row g-4"><div class="col-lg-7"><section class="admin-card"><div class="admin-card-header"><h2 class="h3 mb-0">Biodata siswa</h2></div><div class="admin-card-body"><dl class="row mb-0"><dt class="col-sm-4">NIS</dt><dd class="col-sm-8">{{ $student->nis ?: '—' }}</dd><dt class="col-sm-4">Jenis kelamin</dt><dd class="col-sm-8">{{ $student->gender->label() }}</dd><dt class="col-sm-4">Agama</dt><dd class="col-sm-8">{{ $student->religion?->label() ?? '—' }}</dd><dt class="col-sm-4">Tempat, tanggal lahir</dt><dd class="col-sm-8">{{ $student->birth_place ?: '—' }}{{ $student->birth_date ? ', '.$student->birth_date->translatedFormat('d F Y') : '' }}</dd><dt class="col-sm-4">Alamat</dt><dd class="col-sm-8">{{ $student->address ?: '—' }}</dd><dt class="col-sm-4">Orang tua/wali</dt><dd class="col-sm-8">{{ $student->parent_name ?: '—' }}<span class="d-block small text-muted-warm">{{ $student->parent_phone }}</span></dd><dt class="col-sm-4">Username</dt><dd class="col-sm-8">{{ $student->user->username }}</dd><dt class="col-sm-4">Login terakhir</dt><dd class="col-sm-8">{{ $student->user->last_login_at?->translatedFormat('d F Y H:i') ?: 'Belum pernah' }}</dd></dl></div></section></div><div class="col-lg-5"><section class="admin-card"><div class="admin-card-header"><h2 class="h3 mb-0">Riwayat kelas</h2></div><div class="admin-card-body">@forelse($student->enrollments->sortByDesc('enrolled_at') as $enrollment)<div class="py-2 border-bottom"><strong>{{ $enrollment->schoolClass->name }}</strong><span class="d-block small text-muted-warm">{{ $enrollment->schoolClass->academicPeriod->academic_year }} · {{ $enrollment->schoolClass->academicPeriod->semester->label() }} · {{ ucfirst($enrollment->status->value) }}</span></div>@empty<p class="text-muted-warm mb-0">Belum memiliki riwayat penempatan kelas.</p>@endforelse</div><div class="admin-card-footer"><form action="{{ route('admin.students.destroy', $student) }}" method="post" data-confirm="Hapus data siswa {{ $student->name }}? Aksi hanya berhasil bila belum memiliki riwayat kelas.">@csrf @method('DELETE')<button class="btn btn-outline-danger w-100" type="submit">Hapus Jika Aman</button></form></div></section></div></div>
@endsection
