@extends('layouts.admin')

@php($editing = $schoolClass->exists)
@section('title', ($editing ? 'Edit' : 'Tambah').' Kelas — Panel Admin')
@section('admin_page', 'classes')

@section('content')
    <header class="admin-page-head"><div class="admin-breadcrumb"><span><a href="{{ route('admin.dashboard') }}">Admin</a></span><span><a href="{{ route('admin.classes.index') }}">Kelas &amp; Penempatan</a></span><span>{{ $editing ? 'Edit' : 'Tambah' }}</span></div><span class="eyebrow">Form kelas</span><h1>{{ $editing ? 'Edit kelas.' : 'Tambah kelas.' }}</h1><p class="text-muted-warm mb-0">Nama kelas unik pada setiap periode. Wali kelas hanya dapat dipilih dari guru aktif.</p></header>
    @include('admin.partials.validation-errors')
    <form action="{{ $editing ? route('admin.classes.update', $schoolClass) : route('admin.classes.store') }}" method="post">@csrf @if($editing) @method('PUT') @endif
        <section class="admin-card"><div class="admin-card-body"><div class="row g-3">
            <div class="col-md-6"><label class="form-label" for="name">Nama kelas <span class="required-mark">*</span></label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $schoolClass->name) }}" placeholder="XI IPA 1" required>@error('name') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
            <div class="col-md-6"><label class="form-label" for="academic_period_id">Periode <span class="required-mark">*</span></label><select class="form-select @error('academic_period_id') is-invalid @enderror" id="academic_period_id" name="academic_period_id" required><option value="">Pilih periode</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected((int) old('academic_period_id', $schoolClass->academic_period_id) === $period->id)>{{ $period->academic_year }} · {{ $period->semester->label() }}{{ $period->is_active ? ' (aktif)' : '' }}</option>@endforeach</select>@error('academic_period_id') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
            <div class="col-md-4"><label class="form-label" for="grade_level">Tingkat <span class="required-mark">*</span></label><select class="form-select @error('grade_level') is-invalid @enderror" id="grade_level" name="grade_level" required><option value="">Pilih tingkat</option>@for($grade = 10; $grade <= 12; $grade++)<option value="{{ $grade }}" @selected((int) old('grade_level', $schoolClass->grade_level) === $grade)>Kelas {{ $grade }}</option>@endfor</select>@error('grade_level') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
            <div class="col-md-4"><label class="form-label" for="room">Ruang utama</label><input class="form-control @error('room') is-invalid @enderror" id="room" name="room" value="{{ old('room', $schoolClass->room) }}" placeholder="R-11">@error('room') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
            <div class="col-md-4"><label class="form-label" for="homeroom_teacher_id">Wali kelas</label><select class="form-select @error('homeroom_teacher_id') is-invalid @enderror" id="homeroom_teacher_id" name="homeroom_teacher_id"><option value="">Belum ditentukan</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}" @selected((int) old('homeroom_teacher_id', $schoolClass->homeroom_teacher_id) === $teacher->id)>{{ $teacher->name }}{{ $teacher->is_active ? '' : ' (nonaktif)' }}</option>@endforeach</select>@error('homeroom_teacher_id') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
            <div class="col-12"><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked(old('is_active', $schoolClass->exists ? $schoolClass->is_active : true))><label class="form-check-label" for="is_active">Kelas aktif dan dapat dipakai untuk penempatan serta penugasan baru</label></div></div>
        </div></div><div class="admin-card-footer d-flex flex-wrap justify-content-between gap-2">@if($editing)<button class="btn btn-outline-danger" type="submit" form="delete-class">Hapus Jika Aman</button>@else<span></span>@endif<div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="{{ $editing ? route('admin.classes.show', $schoolClass) : route('admin.classes.index') }}">Batal</a><button class="btn btn-primary" type="submit">Simpan Kelas</button></div></div></section>
    </form>
    @if($editing)<form id="delete-class" action="{{ route('admin.classes.destroy', $schoolClass) }}" method="post" data-confirm="Hapus kelas {{ $schoolClass->name }}? Aksi hanya berhasil bila tidak memiliki riwayat penempatan atau penugasan.">@csrf @method('DELETE')</form>@endif
@endsection
