@extends('layouts.admin')

@section('title', $schoolClass->name.' — Kelas & Penempatan')
@section('admin_page', 'classes')

@section('content')
    <header class="admin-page-head"><div class="admin-breadcrumb"><span><a href="{{ route('admin.dashboard') }}">Admin</a></span><span><a href="{{ route('admin.classes.index') }}">Kelas &amp; Penempatan</a></span><span>Detail</span></div><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3"><div><span class="eyebrow">Kelas terpilih</span><h1>{{ $schoolClass->name }}</h1><p class="text-muted-warm mb-0">{{ $schoolClass->academicPeriod->academic_year }} · {{ $schoolClass->academicPeriod->semester->label() }} · Tingkat {{ $schoolClass->grade_level }}</p></div><div class="d-flex flex-wrap gap-2"><button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#placementModal" @disabled($availableStudents->isEmpty() || ! $schoolClass->is_active)>+ Tempatkan Siswa</button><a class="btn btn-outline-primary" href="{{ route('admin.classes.edit', $schoolClass) }}">Edit Kelas</a></div></div></header>
    @include('admin.partials.validation-errors')
    @php
        $today = now();
        $periodStart = $schoolClass->academicPeriod->start_date;
        $periodEnd = $schoolClass->academicPeriod->end_date;
        $defaultEnrollmentDate = $today->lt($periodStart)
            ? $periodStart
            : ($today->gt($periodEnd) ? $periodEnd : $today);
    @endphp
    <div class="row g-4"><div class="col-xl-4"><section class="admin-card h-100"><div class="admin-card-header"><h2 class="h3 mb-0">Ringkasan kelas</h2><span class="badge {{ $schoolClass->is_active ? 'badge-soft-success' : 'text-bg-secondary' }}">{{ $schoolClass->is_active ? 'Aktif' : 'Nonaktif' }}</span></div><div class="admin-card-body"><dl class="row mb-0"><dt class="col-5">Wali kelas</dt><dd class="col-7">{{ $schoolClass->homeroomTeacher?->name ?: 'Belum ditentukan' }}</dd><dt class="col-5">Ruang utama</dt><dd class="col-7">{{ $schoolClass->room ?: '—' }}</dd><dt class="col-5">Periode</dt><dd class="col-7">{{ $schoolClass->academicPeriod->academic_year }}<span class="d-block small text-muted-warm">{{ $schoolClass->academicPeriod->semester->label() }}</span></dd><dt class="col-5">Siswa aktif</dt><dd class="col-7">{{ $enrollments->total() }}</dd></dl></div></section></div>
        <div class="col-xl-8"><section class="admin-card"><div class="admin-card-header"><div><span class="eyebrow">Penempatan aktif</span><h2 class="h3 mb-0">Daftar siswa</h2></div></div>
            @if($enrollments->isEmpty())
                <div class="empty-state m-3"><span class="empty-state-mark">—</span><span class="eyebrow">{{ $schoolClass->name }}</span><h2>Kelas belum memiliki siswa.</h2><p class="text-muted-warm">Tempatkan siswa aktif untuk periode ini tanpa menghapus riwayat periode sebelumnya.</p>@if($availableStudents->isNotEmpty() && $schoolClass->is_active)<button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#placementModal">+ Tempatkan Siswa</button>@endif</div>
            @else
                <div class="table-responsive table-responsive-stack"><table class="table table-admin align-middle mb-0"><thead><tr><th>Siswa</th><th>NISN</th><th>Sejak</th><th>Pindah kelas</th><th class="text-end">Keluarkan</th></tr></thead><tbody>@foreach($enrollments as $enrollment)
                    @php
                        $actionMinimum = $enrollment->enrolled_at->gt($periodStart) ? $enrollment->enrolled_at : $periodStart;
                        $actionDefault = $today->lt($actionMinimum) ? $actionMinimum : ($today->gt($periodEnd) ? $periodEnd : $today);
                    @endphp
                    <tr><td data-label="Siswa"><strong>{{ $enrollment->student->name }}</strong></td><td data-label="NISN">{{ $enrollment->student->nisn }}</td><td data-label="Sejak">{{ $enrollment->enrolled_at->translatedFormat('d M Y') }}</td><td data-label="Pindah kelas">@if($targetClasses->isNotEmpty())<form action="{{ route('admin.class-enrollments.transfer', [$schoolClass, $enrollment]) }}" method="post" class="d-flex flex-column gap-2" data-confirm="Pindahkan {{ $enrollment->student->name }} dari {{ $schoolClass->name }}?">@csrf @method('PATCH')<select class="form-select form-select-sm" name="target_class_id" aria-label="Kelas tujuan {{ $enrollment->student->name }}" required><option value="">Pilih tujuan</option>@foreach($targetClasses as $targetClass)<option value="{{ $targetClass->id }}">{{ $targetClass->name }}</option>@endforeach</select><div class="d-flex flex-column flex-sm-row gap-2"><input class="form-control form-control-sm" name="enrolled_at" type="date" min="{{ $actionMinimum->format('Y-m-d') }}" max="{{ $periodEnd->format('Y-m-d') }}" value="{{ $actionDefault->format('Y-m-d') }}" aria-label="Tanggal pindah {{ $enrollment->student->name }}" required><button class="btn btn-sm btn-outline-primary" type="submit">Pindah</button></div></form>@else<span class="small text-muted-warm">Tidak ada kelas tujuan aktif</span>@endif</td><td data-label="Keluarkan" class="text-end"><form action="{{ route('admin.class-enrollments.destroy', [$schoolClass, $enrollment]) }}" method="post" class="d-flex flex-column flex-sm-row justify-content-end gap-2" data-confirm="Keluarkan {{ $enrollment->student->name }} dari {{ $schoolClass->name }}? Riwayat tetap disimpan.">@csrf @method('DELETE')<input class="form-control form-control-sm" name="ended_at" type="date" min="{{ $actionMinimum->format('Y-m-d') }}" max="{{ $periodEnd->format('Y-m-d') }}" value="{{ $actionDefault->format('Y-m-d') }}" aria-label="Tanggal keluar {{ $enrollment->student->name }}" required><button class="btn btn-sm btn-outline-danger" type="submit">Keluarkan</button></form></td></tr>@endforeach</tbody></table></div>@if($enrollments->hasPages())<div class="admin-card-footer">{{ $enrollments->links() }}</div>@endif
            @endif
        </section></div></div>

    <section class="admin-card mt-4"><div class="admin-card-header"><div><span class="eyebrow">Audit penempatan</span><h2 class="h3 mb-0">Riwayat kelas</h2></div><span class="badge text-bg-secondary">{{ $enrollmentHistory->total() }} riwayat</span></div>
        @if($enrollmentHistory->isEmpty())
            <div class="admin-card-body"><p class="text-muted-warm mb-0">Belum ada riwayat pindah atau selesai pada kelas ini.</p></div>
        @else
            <div class="table-responsive table-responsive-stack"><table class="table table-admin align-middle mb-0"><thead><tr><th>Siswa</th><th>NISN</th><th>Status</th><th>Mulai</th><th>Selesai</th></tr></thead><tbody>@foreach($enrollmentHistory as $history)<tr><td data-label="Siswa"><strong>{{ $history->student->name }}</strong></td><td data-label="NISN">{{ $history->student->nisn }}</td><td data-label="Status"><span class="badge {{ $history->status === \App\Enums\EnrollmentStatus::Transferred ? 'text-bg-warning' : 'text-bg-secondary' }}">{{ $history->status->label() }}</span></td><td data-label="Mulai">{{ $history->enrolled_at->translatedFormat('d M Y') }}</td><td data-label="Selesai">{{ $history->ended_at?->translatedFormat('d M Y') ?: '—' }}</td></tr>@endforeach</tbody></table></div>@if($enrollmentHistory->hasPages())<div class="admin-card-footer">{{ $enrollmentHistory->links() }}</div>@endif
        @endif
    </section>

    <div class="modal fade" id="placementModal" tabindex="-1" aria-labelledby="placementModalLabel" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><form action="{{ route('admin.class-enrollments.store', $schoolClass) }}" method="post">@csrf<div class="modal-header"><div><span class="eyebrow">{{ $schoolClass->name }}</span><h2 class="modal-title h3" id="placementModalLabel">Tambah siswa ke kelas</h2></div><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Tutup"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label" for="student_ids">Siswa belum ditempatkan <span class="required-mark">*</span></label><select class="form-select" id="student_ids" name="student_ids[]" multiple size="8" required>@foreach($availableStudents as $student)<option value="{{ $student->id }}">{{ $student->name }} · {{ $student->nisn }}</option>@endforeach</select><div class="form-text">Gunakan Ctrl/Cmd untuk memilih lebih dari satu siswa.</div></div><div><label class="form-label" for="enrolled_at">Tanggal penempatan <span class="required-mark">*</span></label><input class="form-control" id="enrolled_at" name="enrolled_at" type="date" min="{{ $schoolClass->academicPeriod->start_date->format('Y-m-d') }}" max="{{ $schoolClass->academicPeriod->end_date->format('Y-m-d') }}" value="{{ $defaultEnrollmentDate->format('Y-m-d') }}" required></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary" type="submit">Tambahkan ke Kelas</button></div></form></div></div></div>
@endsection
