@extends('layouts.admin')

@php($editing = $teachingAssignment->exists)
@section('title', ($editing ? 'Edit' : 'Tambah').' Penugasan — Panel Admin')
@section('admin_page', 'assignments')

@section('content')
    <header class="admin-page-head"><div class="admin-breadcrumb"><span><a href="{{ route('admin.dashboard') }}">Admin</a></span><span><a href="{{ route('admin.assignments.index') }}">Penugasan Mengajar</a></span><span>{{ $editing ? 'Edit' : 'Tambah' }}</span></div><span class="eyebrow">Guru · mapel · kelas</span><h1>{{ $editing ? 'Edit penugasan.' : 'Tambah penugasan.' }}</h1><p class="text-muted-warm mb-0">Pilihan hanya memuat guru, mata pelajaran, dan kelas aktif.</p></header>
    @include('admin.partials.validation-errors')
    @if($identityLocked)<div class="alert alert-warning" role="status">Penugasan sudah digunakan oleh jadwal. Kelas, mata pelajaran, dan guru dikunci untuk menjaga histori; status aktif tetap dapat diubah.</div>@endif
    <form action="{{ $editing ? route('admin.assignments.update', $teachingAssignment) : route('admin.assignments.store') }}" method="post">@csrf @if($editing) @method('PUT') @endif
        <section class="admin-card"><div class="admin-card-body"><div class="row g-3">
            <div class="col-lg-4">@if($identityLocked)<input type="hidden" name="class_id" value="{{ $teachingAssignment->class_id }}">@endif<label class="form-label" for="class_id">Kelas <span class="required-mark">*</span></label><select class="form-select @error('class_id') is-invalid @enderror" id="class_id" name="class_id" required @disabled($identityLocked)><option value="">Pilih kelas</option>@foreach($classes as $schoolClass)<option value="{{ $schoolClass->id }}" @selected((int) old('class_id', $teachingAssignment->class_id) === $schoolClass->id)>{{ $schoolClass->name }} · {{ $schoolClass->academicPeriod->academic_year }} {{ $schoolClass->academicPeriod->semester->label() }}</option>@endforeach</select>@error('class_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-lg-4">@if($identityLocked)<input type="hidden" name="subject_id" value="{{ $teachingAssignment->subject_id }}">@endif<label class="form-label" for="subject_id">Mata pelajaran <span class="required-mark">*</span></label><select class="form-select @error('subject_id') is-invalid @enderror" id="subject_id" name="subject_id" required @disabled($identityLocked)><option value="">Pilih mata pelajaran</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected((int) old('subject_id', $teachingAssignment->subject_id) === $subject->id)>{{ $subject->code }} · {{ $subject->name }}</option>@endforeach</select>@error('subject_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-lg-4">@if($identityLocked)<input type="hidden" name="teacher_id" value="{{ $teachingAssignment->teacher_id }}">@endif<label class="form-label" for="teacher_id">Guru pengampu <span class="required-mark">*</span></label><select class="form-select @error('teacher_id') is-invalid @enderror" id="teacher_id" name="teacher_id" required @disabled($identityLocked)><option value="">Pilih guru</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}" @selected((int) old('teacher_id', $teachingAssignment->teacher_id) === $teacher->id)>{{ $teacher->name }}</option>@endforeach</select>@error('teacher_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-12"><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked(old('is_active', $editing ? $teachingAssignment->is_active : true))><label class="form-check-label" for="is_active">Penugasan aktif dan dapat digunakan pada jadwal</label></div></div>
        </div></div><div class="admin-card-footer d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.assignments.index') }}">Batal</a><button class="btn btn-primary" type="submit">Simpan Penugasan</button></div></section>
    </form>
@endsection
