@extends('layouts.admin')

@php($editing = $teacher->exists)
@section('title', ($editing ? 'Edit' : 'Tambah').' Guru — Panel Admin')
@section('admin_page', 'teachers')

@section('content')
    <header class="admin-page-head"><div class="admin-breadcrumb"><span><a href="{{ route('admin.dashboard') }}">Admin</a></span><span><a href="{{ route('admin.teachers.index') }}">Guru</a></span><span>{{ $editing ? 'Edit' : 'Tambah' }}</span></div><span class="eyebrow">Tenaga pendidik</span><h1>{{ $editing ? 'Edit data guru.' : 'Tambah guru.' }}</h1><p class="text-muted-warm mb-0">Tidak ada username, password, atau role login untuk guru.</p></header>
    @include('admin.partials.validation-errors')
    <form action="{{ $editing ? route('admin.teachers.update', $teacher) : route('admin.teachers.store') }}" method="post" enctype="multipart/form-data">@csrf @if($editing) @method('PUT') @endif
        <section class="admin-card"><div class="admin-card-header"><div><span class="eyebrow">Data guru</span><h2 class="h3 mb-0">Biodata dan direktori</h2></div></div><div class="admin-card-body"><div class="row g-4"><div class="col-lg-8"><div class="row g-3">
            <div class="col-md-8"><label class="form-label" for="name">Nama lengkap &amp; gelar <span class="required-mark">*</span></label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $teacher->name) }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="nip">NIP</label><input class="form-control @error('nip') is-invalid @enderror" id="nip" name="nip" value="{{ old('nip', $teacher->nip) }}">@error('nip')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="gender">Jenis kelamin <span class="required-mark">*</span></label><select class="form-select @error('gender') is-invalid @enderror" id="gender" name="gender" required><option value="">Pilih</option>@foreach($genders as $gender)<option value="{{ $gender->value }}" @selected(old('gender', $teacher->gender?->value) === $gender->value)>{{ $gender->label() }}</option>@endforeach</select>@error('gender')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="birth_place">Tempat lahir</label><input class="form-control" id="birth_place" name="birth_place" value="{{ old('birth_place', $teacher->birth_place) }}"></div>
            <div class="col-md-4"><label class="form-label" for="birth_date">Tanggal lahir</label><input class="form-control @error('birth_date') is-invalid @enderror" id="birth_date" name="birth_date" type="date" value="{{ old('birth_date', $teacher->birth_date?->format('Y-m-d')) }}">@error('birth_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label class="form-label" for="email">Email</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email', $teacher->email) }}">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label class="form-label" for="phone">Telepon</label><input class="form-control" id="phone" name="phone" value="{{ old('phone', $teacher->phone) }}"></div>
            <div class="col-12"><label class="form-label" for="address">Alamat</label><textarea class="form-control" id="address" name="address" rows="3">{{ old('address', $teacher->address) }}</textarea></div>
            <div class="col-12"><label class="form-label" for="public_title">Bidang/judul publik <span class="required-mark">*</span></label><input class="form-control @error('public_title') is-invalid @enderror" id="public_title" name="public_title" value="{{ old('public_title', $teacher->public_title) }}" placeholder="Contoh: Guru Matematika" required>@error('public_title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked(old('is_active', $teacher->exists ? $teacher->is_active : true))><label class="form-check-label" for="is_active">Guru aktif</label></div></div>
            <div class="col-md-6"><div class="form-check form-switch"><input type="hidden" name="is_public" value="0"><input class="form-check-input" id="is_public" name="is_public" type="checkbox" value="1" @checked(old('is_public', $teacher->exists ? $teacher->is_public : true))><label class="form-check-label" for="is_public">Tampilkan di direktori publik</label></div></div>
        </div></div><div class="col-lg-4"><div class="upload-zone {{ $teacher->photo_path ? 'has-preview' : '' }}" id="teacherPhotoPreview" @if($teacher->photo_path) style="background-image:url('{{ asset('storage/'.$teacher->photo_path) }}')" @endif><span>{{ $teacher->photo_path ? 'Foto saat ini' : 'Foto guru opsional' }}</span></div><label class="form-label mt-3" for="photo">Foto profil</label><input class="form-control @error('photo') is-invalid @enderror" id="photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp" data-image-preview="teacherPhotoPreview">@error('photo')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">JPEG, PNG, atau WebP. Maksimal 2 MB.</div></div></div></div>
        <div class="admin-card-footer d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.teachers.index') }}">Batal</a><button class="btn btn-primary" type="submit">Simpan Guru</button></div></section>
    </form>
@endsection
