@extends('layouts.admin')

@section('title', $teacher->name.' — Data Guru')
@section('admin_page', 'teachers')

@section('content')
    <header class="admin-page-head"><div class="admin-breadcrumb"><span><a href="{{ route('admin.dashboard') }}">Admin</a></span><span><a href="{{ route('admin.teachers.index') }}">Guru</a></span><span>Detail</span></div><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3"><div><span class="eyebrow">Detail tenaga pendidik</span><h1>{{ $teacher->name }}</h1><p class="text-muted-warm mb-0">{{ $teacher->public_title }}</p></div><a class="btn btn-primary" href="{{ route('admin.teachers.edit', $teacher) }}">Edit Guru</a></div></header>
    <div class="row g-4"><div class="col-lg-8"><section class="admin-card"><div class="admin-card-header"><h2 class="h3 mb-0">Biodata guru</h2></div><div class="admin-card-body"><dl class="row mb-0"><dt class="col-sm-4">NIP</dt><dd class="col-sm-8">{{ $teacher->nip ?: '—' }}</dd><dt class="col-sm-4">Jenis kelamin</dt><dd class="col-sm-8">{{ $teacher->gender->label() }}</dd><dt class="col-sm-4">Tempat, tanggal lahir</dt><dd class="col-sm-8">{{ $teacher->birth_place ?: '—' }}{{ $teacher->birth_date ? ', '.$teacher->birth_date->translatedFormat('d F Y') : '' }}</dd><dt class="col-sm-4">Email</dt><dd class="col-sm-8">{{ $teacher->email ?: '—' }}</dd><dt class="col-sm-4">Telepon</dt><dd class="col-sm-8">{{ $teacher->phone ?: '—' }}</dd><dt class="col-sm-4">Alamat</dt><dd class="col-sm-8">{{ $teacher->address ?: '—' }}</dd></dl></div></section></div><div class="col-lg-4"><section class="admin-card"><div class="admin-card-header"><h2 class="h3 mb-0">Status &amp; relasi</h2></div><div class="admin-card-body"><p><span class="badge {{ $teacher->is_active ? 'badge-soft-success' : 'text-bg-light' }}">{{ $teacher->is_active ? 'Aktif' : 'Nonaktif' }}</span> <span class="badge {{ $teacher->is_public ? 'badge-soft-success' : 'text-bg-light' }}">{{ $teacher->is_public ? 'Tampil publik' : 'Tidak publik' }}</span></p><ul class="list-unstyled mb-0"><li class="py-2 border-bottom">{{ $teacher->homeroom_classes_count }} kelas sebagai wali</li><li class="py-2 border-bottom">{{ $teacher->teaching_assignments_count }} penugasan mengajar</li><li class="py-2">{{ $teacher->organization_memberships_count }} posisi organisasi</li></ul></div><div class="admin-card-footer"><form action="{{ route('admin.teachers.destroy', $teacher) }}" method="post" data-confirm="Hapus permanen data {{ $teacher->name }}? Aksi hanya berhasil bila tidak ada relasi akademik.">@csrf @method('DELETE')<button class="btn btn-outline-danger w-100" type="submit">Hapus Jika Aman</button></form></div></section></div></div>
@endsection
